### ISSUE TITLE
Method Inertia\ResponseFactory::composer does not exist.

### ISSUE THREAD

**Issue by Kreshnik** [ambengers/kinetic#6]
After installing the package, I am receiving the following exception.
```
Method Inertia\ResponseFactory::composer does not exist.
```

I registered a composer in the `AppServiceProvider` `boot` method.
```
public function boot()
{
    Inertia::composer(Enum::Dashboard, CourseComposer::class);
}
```

I am using **Laravel** version `9.19`

**Comment by ambengers** [comment]
I am unable to replicate this issue with `Laravel 9.19` and `Inertia-Laravel 0.6.4` (latest).

If you can provide a sample repository that replicates this issue I will take a look and investigate.

Closing this for now.
